#!/bin/bash
# ==============================================================================
# Step 3: Application Load Balancer + Target Groups
# ==============================================================================
set -e
source "$(dirname "$0")/env.sh"
source "$(dirname "$0")/network-outputs.env"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 3: Setting Up Application Load Balancer"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ─── Create ALB ───
echo "⚖️  Creating Application Load Balancer..."
ALB_ARN=$(aws elbv2 create-load-balancer \
    --name "${ALB_NAME}" \
    --subnets "${PUBLIC_SUBNET_1}" "${PUBLIC_SUBNET_2}" \
    --security-groups "${ALB_SG}" \
    --scheme internet-facing \
    --type application \
    --ip-address-type ipv4 \
    --query 'LoadBalancers[0].LoadBalancerArn' --output text \
    --region "${AWS_REGION}")
echo "  ALB ARN: ${ALB_ARN}"

ALB_DNS=$(aws elbv2 describe-load-balancers \
    --load-balancer-arns "${ALB_ARN}" \
    --query 'LoadBalancers[0].DNSName' --output text \
    --region "${AWS_REGION}")
echo "  ALB DNS: ${ALB_DNS}"

# ─── Create Target Groups ───
echo "🎯 Creating target groups..."

# Backend target group
TG_BACKEND_ARN=$(aws elbv2 create-target-group \
    --name "${TG_BACKEND_NAME}" \
    --protocol HTTP \
    --port 8000 \
    --vpc-id "${VPC_ID}" \
    --target-type ip \
    --health-check-path "/api/health" \
    --health-check-interval-seconds 30 \
    --health-check-timeout-seconds 5 \
    --healthy-threshold-count 2 \
    --unhealthy-threshold-count 3 \
    --query 'TargetGroups[0].TargetGroupArn' --output text \
    --region "${AWS_REGION}")
echo "  Backend TG: ${TG_BACKEND_ARN}"

# Frontend target group
TG_FRONTEND_ARN=$(aws elbv2 create-target-group \
    --name "${TG_FRONTEND_NAME}" \
    --protocol HTTP \
    --port 3000 \
    --vpc-id "${VPC_ID}" \
    --target-type ip \
    --health-check-path "/" \
    --health-check-interval-seconds 30 \
    --health-check-timeout-seconds 5 \
    --healthy-threshold-count 2 \
    --unhealthy-threshold-count 3 \
    --query 'TargetGroups[0].TargetGroupArn' --output text \
    --region "${AWS_REGION}")
echo "  Frontend TG: ${TG_FRONTEND_ARN}"

# ─── Create Listeners ───
echo "👂 Creating listeners..."

# HTTP Listener - default to frontend
aws elbv2 create-listener \
    --load-balancer-arn "${ALB_ARN}" \
    --protocol HTTP \
    --port 80 \
    --default-actions Type=forward,TargetGroupArn="${TG_FRONTEND_ARN}" \
    --region "${AWS_REGION}" > /dev/null

LISTENER_ARN=$(aws elbv2 describe-listeners \
    --load-balancer-arn "${ALB_ARN}" \
    --query 'Listeners[0].ListenerArn' --output text \
    --region "${AWS_REGION}")

# Route /api/* to backend
aws elbv2 create-rule \
    --listener-arn "${LISTENER_ARN}" \
    --priority 10 \
    --conditions Field=path-pattern,Values='/api/*' \
    --actions Type=forward,TargetGroupArn="${TG_BACKEND_ARN}" \
    --region "${AWS_REGION}" > /dev/null

echo "  HTTP:80 → Frontend (default)"
echo "  /api/* → Backend"

# ─── Save outputs ───
cat > "$(dirname "$0")/alb-outputs.env" << EOF
# Auto-generated by 03-alb-setup.sh
export ALB_ARN="${ALB_ARN}"
export ALB_DNS="${ALB_DNS}"
export TG_BACKEND_ARN="${TG_BACKEND_ARN}"
export TG_FRONTEND_ARN="${TG_FRONTEND_ARN}"
export LISTENER_ARN="${LISTENER_ARN}"
EOF

echo ""
echo "✅ ALB setup complete!"
echo "   Access your app at: http://${ALB_DNS}"
echo "   Resource IDs saved to infra/alb-outputs.env"
echo ""
echo "📝 Next: Run 04-elasticache-setup.sh"
