#!/bin/bash
# ==============================================================================
# Step 4: ElastiCache (Redis) Cluster
# ==============================================================================
set -e
source "$(dirname "$0")/env.sh"
source "$(dirname "$0")/network-outputs.env"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 4: Setting Up ElastiCache (Redis)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ─── Create subnet group ───
echo "📡 Creating ElastiCache subnet group..."
aws elasticache create-cache-subnet-group \
    --cache-subnet-group-name "${PROJECT_NAME}-redis-subnet" \
    --cache-subnet-group-description "Subnet group for ${PROJECT_NAME} Redis" \
    --subnet-ids "${PRIVATE_SUBNET_1}" "${PRIVATE_SUBNET_2}" \
    --region "${AWS_REGION}" > /dev/null

# ─── Create Redis cluster ───
echo "🗄️  Creating ElastiCache Redis cluster..."
aws elasticache create-cache-cluster \
    --cache-cluster-id "${ELASTICACHE_CLUSTER_NAME}" \
    --cache-node-type "${ELASTICACHE_NODE_TYPE}" \
    --engine redis \
    --engine-version "7.0" \
    --num-cache-nodes 1 \
    --cache-subnet-group-name "${PROJECT_NAME}-redis-subnet" \
    --security-group-ids "${REDIS_SG}" \
    --tags Key=Project,Value="${PROJECT_NAME}" \
    --region "${AWS_REGION}" > /dev/null

echo "  ⏳ Waiting for Redis cluster to become available..."
aws elasticache wait cache-cluster-available \
    --cache-cluster-id "${ELASTICACHE_CLUSTER_NAME}" \
    --region "${AWS_REGION}"

# Get Redis endpoint
REDIS_ENDPOINT=$(aws elasticache describe-cache-clusters \
    --cache-cluster-id "${ELASTICACHE_CLUSTER_NAME}" \
    --show-cache-node-info \
    --query 'CacheClusters[0].CacheNodes[0].Endpoint.Address' --output text \
    --region "${AWS_REGION}")

REDIS_PORT=$(aws elasticache describe-cache-clusters \
    --cache-cluster-id "${ELASTICACHE_CLUSTER_NAME}" \
    --show-cache-node-info \
    --query 'CacheClusters[0].CacheNodes[0].Endpoint.Port' --output text \
    --region "${AWS_REGION}")

REDIS_URL="redis://${REDIS_ENDPOINT}:${REDIS_PORT}"

# ─── Save outputs ───
cat > "$(dirname "$0")/elasticache-outputs.env" << EOF
# Auto-generated by 04-elasticache-setup.sh
export REDIS_ENDPOINT="${REDIS_ENDPOINT}"
export REDIS_PORT="${REDIS_PORT}"
export REDIS_URL="${REDIS_URL}"
EOF

echo ""
echo "✅ ElastiCache Redis cluster created!"
echo "   Endpoint: ${REDIS_ENDPOINT}:${REDIS_PORT}"
echo "   URL: ${REDIS_URL}"
echo ""
echo "📝 Next: Run 05-ecs-cluster.sh"
