#!/bin/bash
# ==============================================================================
# Step 5: ECS Cluster + IAM Roles
# ==============================================================================
set -e
source "$(dirname "$0")/env.sh"

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Step 5: Creating ECS Cluster & IAM Roles"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# ─── Create ECS Cluster ───
echo "🏗️  Creating ECS cluster..."
aws ecs create-cluster \
    --cluster-name "${ECS_CLUSTER_NAME}" \
    --capacity-providers FARGATE FARGATE_SPOT \
    --default-capacity-provider-strategy capacityProvider=FARGATE,weight=1 \
    --settings name=containerInsights,value=enabled \
    --tags key=Project,value="${PROJECT_NAME}" \
    --region "${AWS_REGION}" > /dev/null

echo "  Cluster: ${ECS_CLUSTER_NAME}"

# ─── ECS Execution Role (for pulling images, writing logs) ───
echo "👤 Creating ECS execution role..."

TRUST_POLICY='{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": {"Service": "ecs-tasks.amazonaws.com"},
    "Action": "sts:AssumeRole"
  }]
}'

aws iam create-role \
    --role-name "${ECS_EXECUTION_ROLE}" \
    --assume-role-policy-document "${TRUST_POLICY}" \
    --tags Key=Project,Value="${PROJECT_NAME}" \
    2>/dev/null || echo "  ℹ️  Execution role already exists"

aws iam attach-role-policy \
    --role-name "${ECS_EXECUTION_ROLE}" \
    --policy-arn "arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

echo "  Execution Role: ${ECS_EXECUTION_ROLE}"

# ─── ECS Task Role (for application-level AWS access) ───
echo "👤 Creating ECS task role..."

aws iam create-role \
    --role-name "${ECS_TASK_ROLE}" \
    --assume-role-policy-document "${TRUST_POLICY}" \
    --tags Key=Project,Value="${PROJECT_NAME}" \
    2>/dev/null || echo "  ℹ️  Task role already exists"

# Allow task to write to CloudWatch
CLOUDWATCH_POLICY='{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "logs:CreateLogGroup",
        "logs:CreateLogStream",
        "logs:PutLogEvents",
        "logs:DescribeLogGroups",
        "logs:DescribeLogStreams",
        "cloudwatch:PutMetricData"
      ],
      "Resource": "*"
    }
  ]
}'

aws iam put-role-policy \
    --role-name "${ECS_TASK_ROLE}" \
    --policy-name "${PROJECT_NAME}-cloudwatch-policy" \
    --policy-document "${CLOUDWATCH_POLICY}"

echo "  Task Role: ${ECS_TASK_ROLE}"

# ─── Save outputs ───
EXECUTION_ROLE_ARN=$(aws iam get-role --role-name "${ECS_EXECUTION_ROLE}" --query 'Role.Arn' --output text)
TASK_ROLE_ARN=$(aws iam get-role --role-name "${ECS_TASK_ROLE}" --query 'Role.Arn' --output text)

cat > "$(dirname "$0")/ecs-cluster-outputs.env" << EOF
# Auto-generated by 05-ecs-cluster.sh
export ECS_CLUSTER_NAME="${ECS_CLUSTER_NAME}"
export EXECUTION_ROLE_ARN="${EXECUTION_ROLE_ARN}"
export TASK_ROLE_ARN="${TASK_ROLE_ARN}"
EOF

echo ""
echo "✅ ECS Cluster & IAM Roles created!"
echo "   Cluster: ${ECS_CLUSTER_NAME} (with Container Insights)"
echo "   Execution Role: ${EXECUTION_ROLE_ARN}"
echo "   Task Role: ${TASK_ROLE_ARN}"
echo ""
echo "📝 Next: Run 06-task-definitions.sh"
